# -------------------------------------------------------------------------
config:
  # This is the path to the root of the Spack install tree.
  # If you do not want to clutter your homedir set this to another
  # path, eg, in /nesi/project.  Alternatively you can create a symlink
  install_tree:
  root: /home/$user/spack

  build_stage: $root/spack-stage
  test_stage: $root/test
  source_cache: $root/cache
  misc_cache: $root/cache
