# -------------------------------------------------------------------------
# This is the path to the HOME/spack of your Spack install tree.
# If you do not want to clutter your homedir set this to another
# path, eg, in /nesi/project/PROJECTID/$USER/spack.  For the 
# source_cache and misc_cache we recommend pointing to a scratch 
# directory, eg /nesi/nobackup/PROJECTID/$USER/spack-cache
#
config:
  install_tree:
      root: $HOME/spack
  build_stage: 
    - $HOME/spack/spack-stage
  test_stage: $HOME/spack/test
  source_cache: $HOME/spack/cache
  misc_cache: $HOME/spack/cache
