# -------------------------------------------------------------------------
# This is the path to the root of your Spack install tree.
# If you do not want to clutter your homedir set this to another
# path, eg, in /nesi/project/PROJECTID/$user/spack.  For the 
# source_cache and misc_cache we recommend pointing to a scratch 
# directory, eg /nesi/nobackup/PROJECTID/$user/spack-cache
#
config:
  install_tree:
  root: /home/$user/spack

  build_stage: $root/spack-stage
  test_stage: $root/test
  source_cache: $root/cache
  misc_cache: $root/cache
